name: Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    if: ${{ github.repository_owner == 'phuoccss' }}
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v6.0.7

      - uses: actions/setup-node@v6.4.0
        with:
          cache: pnpm
          node-version: lts/*
          check-latest: true
          # registry-url: https://registry.npmjs.org

      # Ensure npm 11.5.1 or later for trusted publishing
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - uses: infisical/secrets-action@v1.0.16
        with:
          method: oidc
          domain: https://app.infisical.com
          project-slug: resonare
          env-slug: prod
          identity-id: e783897d-2572-434c-bc59-d673fae68eda

      - name: Build & deploy
        run: |
          pnpm turbo deploy

      - name: Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: pnpm changeset version && pnpm i --lockfile-only
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish dev version
        if: steps.changesets.outputs.published != 'true'
        run: |
          git checkout main
          pnpm changeset version --snapshot dev
          pnpm changeset publish --tag dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
